version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - dmark-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3001:3001"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/.env:/app/.env
    networks:
      - dmark-network

networks:
  dmark-network:
    driver: bridge
    enable_ipv6: true
